import image from "~/assets/images/Product/image";

const tabs = [
    "Máy tính & laptop",
    "Đồng hồ",
    "Thời trang nam",
    "Thời trang nữ",
    "Mẹ & bé",
    "Nhà cửa & đời sống",
    "Sắc đẹp",
    "Sức khỏe",
    "Giày dép nữ",
    "Thiết bị điện tử",
];

const PanelHeadData = {
    "Máy tính & laptop": [
        {
            img: image.img1,
            title:
                "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
            check: true,
            newText: "new",
            oldCost: "10.000.000",
            newCost: "25.000.000",
            address: "Hai Phong",
            value: 6,
            total: 3,
            displayCartSale: true,
        },
        {
            img: image.img1,
            title:
                "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
            check: true,
            newText: "new",
            oldCost: "10.000.000",
            newCost: "25.000.000",
            address: "Hai Phong",
            value: 6,
            total: 3,
            displayCartSale: true,
        },
        {
            img: image.img1,
            title:
                "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
            check: true,
            newText: "new",
            oldCost: "10.000.000",
            newCost: "25.000.000",
            address: "Hai Phong",
            value: 6,
            total: 3,
            displayCartSale: true,
        },
        {
            img: image.img1,
            title:
                "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
            check: true,
            newText: "new",
            oldCost: "10.000.000",
            newCost: "25.000.000",
            address: "Hai Phong",
            value: 6,
            total: 3,
            displayCartSale: true,
        }
    ],
    "Thời trang nam": [
        {
            img: image.img1,
            title:
                "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
            check: true,
            newText: "new",
            oldCost: "10.000.000",
            newCost: "25.000.000",
            address: "Hai Phong",
            value: 6,
            total: 3,
            displayCartSale: true,
        },
        {
            img: image.img1,
            title:
                "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
            check: true,
            newText: "new",
            oldCost: "10.000.000",
            newCost: "25.000.000",
            address: "Hai Phong",
            value: 6,
            total: 3,
            displayCartSale: true,
        },
        {
            img: image.img1,
            title:
                "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
            check: true,
            newText: "new",
            oldCost: "10.000.000",
            newCost: "25.000.000",
            address: "Hai Phong",
            value: 6,
            total: 3,
            displayCartSale: true,
        },
        {
            img: image.img1,
            title:
                "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
            check: true,
            newText: "new",
            oldCost: "10.000.000",
            newCost: "25.000.000",
            address: "Hai Phong",
            value: 6,
            total: 3,
            displayCartSale: true,
        },
        {
            img: image.img1,
            title:
                "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
            check: true,
            newText: "new",
            oldCost: "10.000.000",
            newCost: "25.000.000",
            address: "Hai Phong",
            value: 6,
            total: 3,
            displayCartSale: true,
        },
    ],
    "Thời trang nữ": [
        {
            img: image.img1,
            title:
                "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
            check: true,
            newText: "new",
            oldCost: "10.000.000",
            newCost: "25.000.000",
            address: "Hai Phong",
            value: 6,
            total: 3,
            displayCartSale: true,
        },
        {
            img: image.img1,
            title:
                "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
            check: true,
            newText: "new",
            oldCost: "10.000.000",
            newCost: "25.000.000",
            address: "Hai Phong",
            value: 6,
            total: 3,
            displayCartSale: true,
        },
        {
            img: image.img1,
            title:
                "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
            check: true,
            newText: "new",
            oldCost: "10.000.000",
            newCost: "25.000.000",
            address: "Hai Phong",
            value: 6,
            total: 3,
            displayCartSale: true,
        },
        {
            img: image.img1,
            title:
                "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
            check: true,
            newText: "new",
            oldCost: "10.000.000",
            newCost: "25.000.000",
            address: "Hai Phong",
            value: 6,
            total: 3,
            displayCartSale: true,
        },
        {
            img: image.img1,
            title:
                "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
            check: true,
            newText: "new",
            oldCost: "10.000.000",
            newCost: "25.000.000",
            address: "Hai Phong",
            value: 6,
            total: 3,
            displayCartSale: true,
        },
    ]
    // "Mẹ & bé": {
    //     img: image.img1,
    //     title:
    //         "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
    //     check: true,
    //     newText: "new",
    //     oldCost: "10.000.000",
    //     newCost: "25.000.000",
    //     address: "Hai Phong",
    //     value: 6,
    //     total: 3,
    //     displayCartSale: true,
    // },

    // "Nhà cửa & đời sống": {
    //     img: image.img1,
    //     title:
    //         "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
    //     check: true,
    //     newText: "new",
    //     oldCost: "10.000.000",
    //     newCost: "25.000.000",
    //     address: "Hai Phong",
    //     value: 6,
    //     total: 3,
    //     displayCartSale: true,
    // },
    // "Sắc đẹp": {
    //     img: image.img1,
    //     title:
    //         "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
    //     check: true,
    //     newText: "new",
    //     oldCost: "10.000.000",
    //     newCost: "25.000.000",
    //     address: "Hai Phong",
    //     value: 6,
    //     total: 3,
    //     displayCartSale: true,
    // },

    // "Sức khỏe": {
    //     img: image.img1,
    //     title:
    //         "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
    //     check: true,
    //     newText: "new",
    //     oldCost: "10.000.000",
    //     newCost: "25.000.000",
    //     address: "Hai Phong",
    //     value: 6,
    //     total: 3,
    //     displayCartSale: true,
    // },
    // "Giày dép nữ": {
    //     img: image.img1,
    //     title:
    //         "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
    //     check: true,
    //     newText: "new",
    //     oldCost: "10.000.000",
    //     newCost: "25.000.000",
    //     address: "Hai Phong",
    //     value: 6,
    //     total: 3,
    //     displayCartSale: true,
    // },
    // "Thiết bị điện tử": {
    //     img: image.img1,
    //     title:
    //         "Sản phẩm này không phải là thuốc nên không thể thay thế thuốc chữa bệnh",
    //     check: true,
    //     newText: "new",
    //     oldCost: "10.000.000",
    //     newCost: "25.000.000",
    //     address: "Hai Phong",
    //     value: 6,
    //     total: 3,
    //     displayCartSale: true,
    // },
};
export { tabs, PanelHeadData };
